Resolving AttributeError: 'NoneType' object has no attribute 'last_price' arised because trade.update_eta() was attempted prior to commit while creating new trade